spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:TRUE}
    properties:
      hibernate:
        format_sql: true

server:
  port: ${SERVER_PORT:8080}